/**
 * รายการไอคอนทั้งหมดที่เลือกใช้ได้ในระบบ
 *
 * ★ ไฟล์นี้ถูกสร้างอัตโนมัติ อย่าแก้มือ ★
 * แก้ที่ scripts/icon-source.mjs แล้วรัน `npm run icons`
 *
 * ค่าที่เก็บลงฐานข้อมูลเป็นสตริงมี prefix เสมอ เช่น "ms:bolt" "emoji:money-bag"
 * "brand:line" "bank:kbank" มี prefix เพื่อให้ย้ายไอคอนข้ามกลุ่มได้โดยค่าที่บันทึกไว้
 * เดิมยังใช้ได้อยู่ และเพื่อไม่ให้ชื่อชนกันเองระหว่างชุด (เช่น shell ที่เป็นทั้งไอคอนและแบรนด์)
 */

/** ไอคอนทั่วไป แบ่งตามกลุ่ม — [ชื่อไฟล์, ชื่อไทย] */
export const ICON_GROUPS = [
  {
    key: "finance", label: "การเงิน", cover: "payments", color: "#12795B",
    items: [
    ["payments", "ชำระเงิน"],
    ["wallet", "กระเป๋าเงิน"],
    ["savings", "เงินออม"],
    ["account_balance", "ธนาคาร"],
    ["credit_card", "บัตรเครดิต"],
    ["currency_exchange", "แลกเปลี่ยนเงิน"],
    ["request_quote", "ใบเสนอราคา"],
    ["receipt_long", "ใบเสร็จ"],
    ["attach_money", "เงิน"],
    ["price_change", "ราคาเปลี่ยน"],
    ["trending_up", "กำไร"],
    ["trending_down", "ขาดทุน"],
    ["account_balance_wallet", "บัญชีเงิน"],
    ["paid", "จ่ายแล้ว"],
    ["sell", "ขายของ"],
    ["redeem", "แต้มสะสม"],
    ["universal_currency", "ธนบัตร"],
    ["point_of_sale", "เครื่องคิดเงิน"],
    ["calculate", "คำนวณ"],
    ["percent", "ดอกเบี้ย"],
    ["universal_currency_alt", "สกุลเงิน"],
    ["handshake", "ดีลธุรกิจ"],
    ],
  },
  {
    key: "food", label: "อาหารและเครื่องดื่ม", cover: "restaurant", color: "#E06A1F",
    items: [
    ["restaurant", "ร้านอาหาร"],
    ["lunch_dining", "เบอร์เกอร์"],
    ["ramen_dining", "ก๋วยเตี๋ยว"],
    ["rice_bowl", "ข้าว"],
    ["local_cafe", "กาแฟ"],
    ["local_bar", "เครื่องดื่มแอลกอฮอล์"],
    ["local_pizza", "พิซซ่า"],
    ["bakery_dining", "เบเกอรี่"],
    ["icecream", "ไอศกรีม"],
    ["egg", "ไข่"],
    ["set_meal", "อาหารชุด"],
    ["kebab_dining", "ปิ้งย่าง"],
    ["brunch_dining", "มื้อสาย"],
    ["liquor", "เหล้า"],
    ["local_dining", "ช้อนส้อม"],
    ["fastfood", "ฟาสต์ฟู้ด"],
    ["cake", "เค้ก"],
    ["coffee", "กาแฟแก้ว"],
    ["takeout_dining", "อาหารกล่อง"],
    ["local_drink", "น้ำดื่ม"],
    ["nutrition", "โภชนาการ"],
    ["grocery", "ของสด"],
    ],
  },
  {
    key: "shopping", label: "ช้อปปิ้ง", cover: "shopping_cart", color: "#D0483C",
    items: [
    ["shopping_cart", "ตะกร้าสินค้า"],
    ["shopping_bag", "ถุงช้อปปิ้ง"],
    ["storefront", "หน้าร้าน"],
    ["local_convenience_store", "ร้านสะดวกซื้อ"],
    ["local_mall", "ห้างสรรพสินค้า"],
    ["label_important", "ป้ายโปรโมชัน"],
    ["inventory_2", "สต๊อกสินค้า"],
    ["package_2", "พัสดุ"],
    ["local_shipping", "ขนส่ง"],
    ["qr_code_scanner", "สแกนจ่าย"],
    ["loyalty", "บัตรสมาชิก"],
    ["percent_discount", "ส่วนลด"],
    ["shopping_basket", "ตะกร้า"],
    ["category", "หมวดสินค้า"],
    ["barcode", "บาร์โค้ด"],
    ["store", "ร้านค้า"],
    ["add_shopping_cart", "เพิ่มลงตะกร้า"],
    ["receipt", "ใบเสร็จรับเงิน"],
    ],
  },
  {
    key: "home", label: "บ้านและที่พัก", cover: "home", color: "#2F8F6B",
    items: [
    ["home", "บ้าน"],
    ["apartment", "คอนโด"],
    ["house", "บ้านเดี่ยว"],
    ["villa", "บ้านพัก"],
    ["bed", "ห้องนอน"],
    ["chair", "เฟอร์นิเจอร์"],
    ["weekend", "โซฟา"],
    ["kitchen", "ห้องครัว"],
    ["bathtub", "ห้องน้ำ"],
    ["local_laundry_service", "ซักผ้า"],
    ["cleaning_services", "ทำความสะอาด"],
    ["yard", "สนามหญ้า"],
    ["door_front", "ประตูบ้าน"],
    ["key", "ค่าเช่า"],
    ["meeting_room", "ห้องเช่า"],
    ["garage", "โรงรถ"],
    ["roofing", "หลังคา"],
    ["table_restaurant", "โต๊ะ"],
    ["light", "โคมไฟ"],
    ["countertops", "เคาน์เตอร์"],
    ],
  },
  {
    key: "build", label: "ก่อสร้างและซ่อมแซม", cover: "construction", color: "#8A6A15",
    items: [
    ["construction", "ก่อสร้าง"],
    ["handyman", "ช่างซ่อม"],
    ["engineering", "วิศวกรรม"],
    ["hardware", "เครื่องมือช่าง"],
    ["carpenter", "งานไม้"],
    ["plumbing", "งานประปา"],
    ["electrical_services", "งานไฟฟ้า"],
    ["format_paint", "สีทาบ้าน"],
    ["foundation", "งานฐานราก"],
    ["architecture", "ออกแบบอาคาร"],
    ["home_repair_service", "กล่องเครื่องมือ"],
    ["forklift", "รถยก"],
    ["fire_extinguisher", "ถังดับเพลิง"],
    ["layers", "ชั้นวัสดุ"],
    ["square_foot", "วัดพื้นที่"],
    ["warehouse", "โกดัง"],
    ["factory", "โรงงาน"],
    ["precision_manufacturing", "เครื่องจักร"],
    ["build", "ประแจ"],
    ["sensors", "งานระบบ"],
    ],
  },
  {
    key: "transport", label: "เดินทางและยานพาหนะ", cover: "directions_car", color: "#3A55C4",
    items: [
    ["directions_car", "รถยนต์"],
    ["two_wheeler", "มอเตอร์ไซค์"],
    ["local_gas_station", "ปั๊มน้ำมัน"],
    ["ev_station", "ชาร์จรถไฟฟ้า"],
    ["local_taxi", "แท็กซี่"],
    ["directions_bus", "รถเมล์"],
    ["train", "รถไฟ"],
    ["subway", "รถไฟฟ้า"],
    ["flight", "เครื่องบิน"],
    ["directions_boat", "เรือ"],
    ["pedal_bike", "จักรยาน"],
    ["local_parking", "ที่จอดรถ"],
    ["car_repair", "ซ่อมรถ"],
    ["car_rental", "เช่ารถ"],
    ["toll", "ทางด่วน"],
    ["traffic", "การจราจร"],
    ["moped", "ส่งของ"],
    ["airport_shuttle", "รถตู้"],
    ["route", "เส้นทาง"],
    ["speed", "ความเร็ว"],
    ],
  },
  {
    key: "bills", label: "ค่าบ้านค่าบิล", cover: "bolt", color: "#A8760B",
    items: [
    ["bolt", "ค่าไฟ"],
    ["water_drop", "ค่าน้ำ"],
    ["wifi", "ค่าอินเทอร์เน็ต"],
    ["router", "เราเตอร์"],
    ["mobile", "ค่าโทรศัพท์"],
    ["tv", "ค่าทีวี"],
    ["local_fire_department", "ค่าแก๊ส"],
    ["propane_tank", "ถังแก๊ส"],
    ["description", "ใบแจ้งหนี้"],
    ["gavel", "ค่าปรับ"],
    ["assured_workload", "ภาษี"],
    ["subscriptions", "ค่าสมาชิกรายเดือน"],
    ["sim_card", "แพ็กเกจซิม"],
    ["lightbulb", "หลอดไฟ"],
    ["ac_unit", "ค่าแอร์"],
    ["delete", "ค่าขยะ"],
    ["shield", "ค่าประกัน"],
    ["health_and_safety", "ประกันสังคม"],
    ["event_repeat", "รายการรายเดือน"],
    ["schedule", "ครบกำหนด"],
    ],
  },
  {
    key: "health", label: "สุขภาพ", cover: "local_hospital", color: "#D9436F",
    items: [
    ["local_hospital", "โรงพยาบาล"],
    ["medical_services", "ค่ารักษา"],
    ["medication", "ค่ายา"],
    ["vaccines", "วัคซีน"],
    ["monitor_heart", "ตรวจสุขภาพ"],
    ["favorite", "หัวใจ"],
    ["fitness_center", "ฟิตเนส"],
    ["self_improvement", "โยคะ"],
    ["directions_run", "วิ่ง"],
    ["sports_soccer", "กีฬา"],
    ["spa", "สปา"],
    ["dentistry", "ทำฟัน"],
    ["visibility", "ตรวจสายตา"],
    ["psychology", "สุขภาพจิต"],
    ["healing", "รักษาแผล"],
    ["emergency", "ฉุกเฉิน"],
    ["bloodtype", "ตรวจเลือด"],
    ["ecg_heart", "คลื่นหัวใจ"],
    ],
  },
  {
    key: "education", label: "การศึกษา", cover: "school", color: "#5E44A0",
    items: [
    ["school", "โรงเรียน"],
    ["menu_book", "หนังสือเรียน"],
    ["book", "หนังสือ"],
    ["auto_stories", "อ่านหนังสือ"],
    ["backpack", "กระเป๋านักเรียน"],
    ["science", "วิทยาศาสตร์"],
    ["translate", "ภาษา"],
    ["workspace_premium", "ประกาศนียบัตร"],
    ["quiz", "แบบทดสอบ"],
    ["draw", "วาดรูป"],
    ["history_edu", "ประวัติศาสตร์"],
    ["biotech", "ห้องแล็บ"],
    ["cast_for_education", "เรียนออนไลน์"],
    ["edit", "เครื่องเขียน"],
    ["library_books", "ห้องสมุด"],
    ],
  },
  {
    key: "work", label: "ธุรกิจและงาน", cover: "work", color: "#2A6A8A",
    items: [
    ["work", "งาน"],
    ["badge", "บัตรพนักงาน"],
    ["groups", "ทีมงาน"],
    ["person", "บุคคล"],
    ["business_center", "ธุรกิจ"],
    ["corporate_fare", "บริษัท"],
    ["assignment", "งานที่ได้รับ"],
    ["task_alt", "งานเสร็จ"],
    ["event_note", "นัดหมาย"],
    ["campaign", "ประชาสัมพันธ์"],
    ["ads_click", "ค่าโฆษณา"],
    ["support_agent", "ฝ่ายบริการ"],
    ["call", "โทรติดต่อ"],
    ["mail", "อีเมล"],
    ["print", "ค่าปริ้น"],
    ["folder", "แฟ้มงาน"],
    ["query_stats", "วิเคราะห์ข้อมูล"],
    ["bar_chart", "กราฟ"],
    ["inventory", "เช็กสต๊อก"],
    ["fact_check", "ตรวจเอกสาร"],
    ],
  },
  {
    key: "fun", label: "บันเทิงและไลฟ์สไตล์", cover: "sports_esports", color: "#B3335C",
    items: [
    ["sports_esports", "เกม"],
    ["movie", "ภาพยนตร์"],
    ["theaters", "โรงหนัง"],
    ["music_note", "ดนตรี"],
    ["headphones", "หูฟัง"],
    ["mic", "ร้องเพลง"],
    ["celebration", "งานฉลอง"],
    ["sports_bar", "ปาร์ตี้"],
    ["photo_camera", "ถ่ายรูป"],
    ["palette", "งานศิลปะ"],
    ["park", "สวนสาธารณะ"],
    ["festival", "เทศกาล"],
    ["confirmation_number", "ตั๋ว"],
    ["stadium", "สนามกีฬา"],
    ["nightlife", "กลางคืน"],
    ["videogame_asset", "อุปกรณ์เกม"],
    ["live_tv", "ดูสด"],
    ["smart_display", "สตรีมมิ่ง"],
    ["content_cut", "ตัดผม"],
    ["checkroom", "เสื้อผ้า"],
    ],
  },
  {
    key: "family", label: "ครอบครัวและสัตว์เลี้ยง", cover: "pets", color: "#C2571F",
    items: [
    ["pets", "สัตว์เลี้ยง"],
    ["family_restroom", "ครอบครัว"],
    ["child_care", "เด็กเล็ก"],
    ["stroller", "รถเข็นเด็ก"],
    ["volunteer_activism", "บริจาค"],
    ["diversity_3", "ชุมชน"],
    ["elderly", "ผู้สูงอายุ"],
    ["pregnant_woman", "ตั้งครรภ์"],
    ["toys", "ของเล่น"],
    ["woman", "ผู้หญิง"],
    ["man", "ผู้ชาย"],
    ["face", "ใบหน้า"],
    ["crib", "เตียงเด็ก"],
    ["sound_detection_dog_barking", "สุนัข"],
    ],
  },
  {
    key: "tech", label: "เทคโนโลยี", cover: "computer", color: "#4A5568",
    items: [
    ["computer", "คอมพิวเตอร์"],
    ["laptop_mac", "โน้ตบุ๊ก"],
    ["devices", "อุปกรณ์"],
    ["keyboard", "คีย์บอร์ด"],
    ["mouse", "เมาส์"],
    ["memory", "ชิป"],
    ["storage", "พื้นที่เก็บข้อมูล"],
    ["cloud", "คลาวด์"],
    ["cloud_upload", "สำรองข้อมูล"],
    ["code", "เขียนโปรแกรม"],
    ["terminal", "เทอร์มินัล"],
    ["dns", "เซิร์ฟเวอร์"],
    ["security", "ความปลอดภัย"],
    ["vpn_key", "ไลเซนส์"],
    ["headset_mic", "เฮดเซ็ต"],
    ["cable", "สายอุปกรณ์"],
    ["battery_charging_full", "แบตเตอรี่"],
    ["usb", "ยูเอสบี"],
    ["smart_toy", "เอไอ"],
    ["print_connect", "เครื่องพิมพ์"],
    ],
  },
  {
    key: "travel", label: "ท่องเที่ยว", cover: "luggage", color: "#0E8AA8",
    items: [
    ["luggage", "กระเป๋าเดินทาง"],
    ["flight_takeoff", "ขึ้นเครื่อง"],
    ["hotel", "โรงแรม"],
    ["beach_access", "ทะเล"],
    ["hiking", "เดินป่า"],
    ["map", "แผนที่"],
    ["location_on", "สถานที่"],
    ["explore", "สำรวจ"],
    ["cabin", "บ้านพักตากอากาศ"],
    ["public", "ต่างประเทศ"],
    ["tour", "ทัวร์"],
    ["landscape", "ธรรมชาติ"],
    ["surfing", "กิจกรรมทางน้ำ"],
    ["downhill_skiing", "เล่นสกี"],
    ["temple_buddhist", "วัด"],
    ["mosque", "มัสยิด"],
    ["church", "โบสถ์"],
    ["castle", "ปราสาท"],
    ],
  },
  {
    key: "misc", label: "ทั่วไป", cover: "label", color: "#7A7F87",
    items: [
    ["label", "ป้ายกำกับ"],
    ["star", "ดาว"],
    ["bookmark", "คั่นหน้า"],
    ["flag", "ธง"],
    ["keep", "ปักหมุด"],
    ["more_horiz", "อื่นๆ"],
    ["help", "ไม่ระบุ"],
    ["info", "ข้อมูล"],
    ["warning", "เตือน"],
    ["check_circle", "เสร็จแล้ว"],
    ["cancel", "ยกเลิก"],
    ["calendar_month", "ปฏิทิน"],
    ["autorenew", "วนซ้ำ"],
    ["sync", "ซิงก์"],
    ["swap_horiz", "โอนย้าย"],
    ["north_east", "เงินออก"],
    ["south_west", "เงินเข้า"],
    ["lock", "ล็อก"],
    ["settings", "ตั้งค่า"],
    ["folder_open", "เปิดแฟ้ม"],
    ["sticky_note_2", "โน้ต"],
    ["group_work", "กลุ่มรวม"],
    ],
  },
]

/**
 * ไอคอนสี (Fluent Emoji Flat) แบ่งตามกลุ่ม — [ชื่อไฟล์, ชื่อไทย]
 * ระบายสีมาในไฟล์แล้ว ย้อมสีทับไม่ได้ ต้องแสดงด้วย <img> ดู iconIsColor()
 */
export const EMOJI_GROUPS = [
  {
    key: "e_money", label: "การเงิน", cover: "money-bag",
    items: [
    ["money-bag", "ถุงเงิน"],
    ["dollar-banknote", "ธนบัตร"],
    ["yen-banknote", "แบงก์เยน"],
    ["coin", "เหรียญ"],
    ["credit-card", "บัตรเครดิต"],
    ["bank", "ธนาคาร"],
    ["money-with-wings", "เงินหาย"],
    ["chart-increasing", "ยอดขึ้น"],
    ["chart-decreasing", "ยอดลง"],
    ["bar-chart", "กราฟแท่ง"],
    ["receipt", "ใบเสร็จ"],
    ["ledger", "สมุดบัญชี"],
    ["abacus", "ลูกคิด"],
    ["gem-stone", "ของมีค่า"],
    ["currency-exchange", "แลกเงิน"],
    ["heavy-dollar-sign", "เครื่องหมายเงิน"],
    ["atm-sign", "ตู้เอทีเอ็ม"],
    ["briefcase", "กระเป๋างาน"],
    ["handshake", "ปิดดีล"],
    ["purse", "กระเป๋าสตางค์"],
    ["hundred-points", "เต็มร้อย"],
    ["locked-with-key", "เงินเก็บ"],
    ],
  },
  {
    key: "e_food", label: "อาหารและเครื่องดื่ม", cover: "steaming-bowl",
    items: [
    ["steaming-bowl", "ก๋วยเตี๋ยว"],
    ["cooked-rice", "ข้าว"],
    ["curry-rice", "ข้าวแกง"],
    ["hamburger", "เบอร์เกอร์"],
    ["pizza", "พิซซ่า"],
    ["french-fries", "เฟรนช์ฟรายส์"],
    ["hot-dog", "ฮอตดอก"],
    ["sandwich", "แซนด์วิช"],
    ["sushi", "ซูชิ"],
    ["bento-box", "ข้าวกล่อง"],
    ["takeout-box", "อาหารใส่กล่อง"],
    ["dumpling", "เกี๊ยว"],
    ["spaghetti", "สปาเกตตี"],
    ["fried-shrimp", "กุ้งทอด"],
    ["cut-of-meat", "เนื้อสัตว์"],
    ["poultry-leg", "ไก่"],
    ["egg", "ไข่"],
    ["cooking", "ทำอาหาร"],
    ["pot-of-food", "หม้อแกง"],
    ["green-salad", "สลัด"],
    ["bread", "ขนมปัง"],
    ["croissant", "ครัวซองต์"],
    ["shortcake", "เค้ก"],
    ["birthday-cake", "เค้กวันเกิด"],
    ["doughnut", "โดนัท"],
    ["cookie", "คุกกี้"],
    ["chocolate-bar", "ช็อกโกแลต"],
    ["candy", "ลูกอม"],
    ["popcorn", "ป๊อปคอร์น"],
    ["ice-cream", "ไอศกรีมถ้วย"],
    ["soft-ice-cream", "ไอศกรีมโคน"],
    ["shaved-ice", "น้ำแข็งไส"],
    ["hot-beverage", "กาแฟร้อน"],
    ["cup-with-straw", "น้ำหวาน"],
    ["bubble-tea", "ชานมไข่มุก"],
    ["tropical-drink", "น้ำปั่น"],
    ["glass-of-milk", "นม"],
    ["teacup-without-handle", "ชา"],
    ["beer-mug", "เบียร์"],
    ["wine-glass", "ไวน์"],
    ["cocktail-glass", "ค็อกเทล"],
    ["watermelon", "แตงโม"],
    ["banana", "กล้วย"],
    ["red-apple", "แอปเปิล"],
    ["grapes", "องุ่น"],
    ["mango", "มะม่วง"],
    ["strawberry", "สตรอว์เบอร์รี"],
    ["cheese-wedge", "ชีส"],
    ["canned-food", "อาหารกระป๋อง"],
    ["hot-pepper", "พริก"],
    ["carrot", "แครอท"],
    ["garlic", "กระเทียม"],
    ["onion", "หัวหอม"],
    ["tomato", "มะเขือเทศ"],
    ],
  },
  {
    key: "e_shopping", label: "ช้อปปิ้งและของใช้", cover: "shopping-bags",
    items: [
    ["shopping-bags", "ถุงช้อปปิ้ง"],
    ["shopping-cart", "รถเข็นซื้อของ"],
    ["basket", "ตะกร้า"],
    ["package", "พัสดุ"],
    ["delivery-truck", "ส่งของ"],
    ["convenience-store", "ร้านสะดวกซื้อ"],
    ["department-store", "ห้างสรรพสินค้า"],
    ["label", "ป้ายราคา"],
    ["wrapped-gift", "ของขวัญ"],
    ["ribbon", "โบว์"],
    ["ticket", "ตั๋ว"],
    ["admission-tickets", "บัตรเข้าชม"],
    ["t-shirt", "เสื้อยืด"],
    ["dress", "ชุดเดรส"],
    ["jeans", "กางเกงยีนส์"],
    ["shorts", "กางเกงขาสั้น"],
    ["coat", "เสื้อโค้ต"],
    ["socks", "ถุงเท้า"],
    ["gloves", "ถุงมือ"],
    ["scarf", "ผ้าพันคอ"],
    ["top-hat", "หมวก"],
    ["billed-cap", "หมวกแก๊ป"],
    ["running-shoe", "รองเท้าผ้าใบ"],
    ["high-heeled-shoe", "รองเท้าส้นสูง"],
    ["mans-shoe", "รองเท้าหนัง"],
    ["thong-sandal", "รองเท้าแตะ"],
    ["handbag", "กระเป๋าถือ"],
    ["backpack", "เป้"],
    ["lipstick", "ลิปสติก"],
    ["nail-polish", "ยาทาเล็บ"],
    ["ring", "แหวน"],
    ["watch", "นาฬิกาข้อมือ"],
    ["glasses", "แว่นตา"],
    ["sunglasses", "แว่นกันแดด"],
    ["mobile-phone", "มือถือ"],
    ["laptop", "โน้ตบุ๊ก"],
    ["scissors", "กรรไกร"],
    ["kitchen-knife", "มีด"],
    ["spoon", "ช้อน"],
    ["chopsticks", "ตะเกียบ"],
    ["fork-and-knife-with-plate", "จานอาหาร"],
    ],
  },
  {
    key: "e_home", label: "บ้านและงานบ้าน", cover: "house-with-garden",
    items: [
    ["house-with-garden", "บ้าน"],
    ["house", "บ้านเดี่ยว"],
    ["houses", "หมู่บ้าน"],
    ["office-building", "อาคาร"],
    ["hotel", "โรงแรม"],
    ["bed", "เตียงนอน"],
    ["couch-and-lamp", "โซฟา"],
    ["chair", "เก้าอี้"],
    ["bathtub", "อ่างอาบน้ำ"],
    ["shower", "ฝักบัว"],
    ["toilet", "ห้องน้ำ"],
    ["broom", "ไม้กวาด"],
    ["sponge", "ฟองน้ำ"],
    ["soap", "สบู่"],
    ["bucket", "ถังน้ำ"],
    ["toothbrush", "แปรงสีฟัน"],
    ["roll-of-paper", "ทิชชู"],
    ["wastebasket", "ถังขยะ"],
    ["door", "ประตู"],
    ["window", "หน้าต่าง"],
    ["key", "กุญแจ"],
    ["old-key", "ค่าเช่า"],
    ["locked", "ล็อก"],
    ["unlocked", "ปลดล็อก"],
    ["light-bulb", "หลอดไฟ"],
    ["electric-plug", "ปลั๊กไฟ"],
    ["potted-plant", "ต้นไม้ในบ้าน"],
    ["seedling", "ต้นกล้า"],
    ["cactus", "กระบองเพชร"],
    ["sunflower", "ดอกทานตะวัน"],
    ["fire-extinguisher", "ถังดับเพลิง"],
    ["mirror", "กระจก"],
    ["plunger", "ที่ปั๊มส้วม"],
    ["mouse-trap", "กับดักหนู"],
    ["sewing-needle", "เข็มเย็บผ้า"],
    ["thread", "ด้าย"],
    ],
  },
  {
    key: "e_build", label: "เครื่องมือและซ่อมแซม", cover: "hammer-and-wrench",
    items: [
    ["hammer-and-wrench", "ซ่อมแซม"],
    ["hammer", "ค้อน"],
    ["wrench", "ประแจ"],
    ["screwdriver", "ไขควง"],
    ["nut-and-bolt", "น็อต"],
    ["gear", "เฟือง"],
    ["toolbox", "กล่องเครื่องมือ"],
    ["carpentry-saw", "เลื่อย"],
    ["paintbrush", "พู่กัน"],
    ["brick", "อิฐ"],
    ["ladder", "บันได"],
    ["construction", "ก่อสร้าง"],
    ["straight-ruler", "ไม้บรรทัด"],
    ["triangular-ruler", "ไม้ฉาก"],
    ["oil-drum", "ถังน้ำมัน"],
    ["magnet", "แม่เหล็ก"],
    ["hammer-and-pick", "งานช่าง"],
    ["safety-vest", "เสื้อกั๊กนิรภัย"],
    ["goggles", "แว่นนิรภัย"],
    ],
  },
  {
    key: "e_transport", label: "เดินทางและขนส่ง", cover: "automobile",
    items: [
    ["automobile", "รถยนต์"],
    ["taxi", "แท็กซี่"],
    ["bus", "รถเมล์"],
    ["minibus", "รถตู้"],
    ["pickup-truck", "รถกระบะ"],
    ["articulated-lorry", "รถบรรทุก"],
    ["sport-utility-vehicle", "รถเอสยูวี"],
    ["racing-car", "รถแข่ง"],
    ["motorcycle", "มอเตอร์ไซค์"],
    ["motor-scooter", "สกู๊ตเตอร์"],
    ["auto-rickshaw", "ตุ๊กตุ๊ก"],
    ["bicycle", "จักรยาน"],
    ["kick-scooter", "สกู๊ตเตอร์ไฟฟ้า"],
    ["fuel-pump", "ปั๊มน้ำมัน"],
    ["train", "รถไฟ"],
    ["metro", "รถไฟฟ้า"],
    ["high-speed-train", "รถไฟความเร็วสูง"],
    ["tram", "รถราง"],
    ["airplane", "เครื่องบิน"],
    ["airplane-departure", "ขาออก"],
    ["airplane-arrival", "ขาเข้า"],
    ["helicopter", "เฮลิคอปเตอร์"],
    ["ship", "เรือใหญ่"],
    ["speedboat", "เรือเร็ว"],
    ["ferry", "เรือข้ามฟาก"],
    ["sailboat", "เรือใบ"],
    ["anchor", "สมอเรือ"],
    ["luggage", "กระเป๋าเดินทาง"],
    ["world-map", "แผนที่"],
    ["round-pushpin", "หมุดสถานที่"],
    ["compass", "เข็มทิศ"],
    ["police-car-light", "ไฟฉุกเฉิน"],
    ["motorway", "ทางหลวง"],
    ["bus-stop", "ป้ายรถเมล์"],
    ["station", "สถานี"],
    ],
  },
  {
    key: "e_bills", label: "บิลและเอกสาร", cover: "high-voltage",
    items: [
    ["high-voltage", "ค่าไฟ"],
    ["droplet", "ค่าน้ำ"],
    ["potable-water", "น้ำดื่ม"],
    ["fire", "แก๊ส"],
    ["telephone", "ค่าโทรศัพท์"],
    ["telephone-receiver", "โทรศัพท์บ้าน"],
    ["antenna-bars", "ค่าเน็ตมือถือ"],
    ["satellite-antenna", "จานดาวเทียม"],
    ["television", "ค่าทีวี"],
    ["wireless", "ไวไฟ"],
    ["calendar", "ปฏิทิน"],
    ["tear-off-calendar", "กำหนดวัน"],
    ["spiral-calendar", "ตารางเดือน"],
    ["alarm-clock", "เตือนเวลา"],
    ["stopwatch", "จับเวลา"],
    ["hourglass-done", "หมดเวลา"],
    ["hourglass-not-done", "รอเวลา"],
    ["envelope", "จดหมาย"],
    ["e-mail", "อีเมล"],
    ["incoming-envelope", "เอกสารเข้า"],
    ["inbox-tray", "รับเข้า"],
    ["outbox-tray", "ส่งออก"],
    ["page-facing-up", "เอกสาร"],
    ["page-with-curl", "ใบแจ้งหนี้"],
    ["clipboard", "คลิปบอร์ด"],
    ["memo", "บันทึกข้อความ"],
    ["spiral-notepad", "สมุดจด"],
    ["bookmark-tabs", "เอกสารหลายใบ"],
    ["pushpin", "ปักหมุด"],
    ["paperclip", "คลิปหนีบ"],
    ["file-folder", "แฟ้ม"],
    ["open-file-folder", "แฟ้มเปิด"],
    ["card-index-dividers", "แฟ้มแบ่งหมวด"],
    ["file-cabinet", "ตู้เอกสาร"],
    ["card-file-box", "กล่องเอกสาร"],
    ["scroll", "สัญญา"],
    ["shield", "ประกัน"],
    ["warning", "เตือน"],
    ["check-mark-button", "เสร็จแล้ว"],
    ["cross-mark", "ยกเลิก"],
    ["prohibited", "ห้าม"],
    ["bell", "แจ้งเตือน"],
    ["bell-with-slash", "ปิดเตือน"],
    ["counterclockwise-arrows-button", "รายการประจำ"],
    ["repeat-button", "ทำซ้ำ"],
    ],
  },
  {
    key: "e_health", label: "สุขภาพและความงาม", cover: "pill",
    items: [
    ["pill", "ยา"],
    ["syringe", "ฉีดยา"],
    ["stethoscope", "หมอ"],
    ["hospital", "โรงพยาบาล"],
    ["ambulance", "รถพยาบาล"],
    ["adhesive-bandage", "พลาสเตอร์"],
    ["thermometer", "วัดไข้"],
    ["face-with-thermometer", "ไม่สบาย"],
    ["drop-of-blood", "เลือด"],
    ["dna", "ดีเอ็นเอ"],
    ["microbe", "เชื้อโรค"],
    ["tooth", "ทำฟัน"],
    ["bone", "กระดูก"],
    ["lungs", "ปอด"],
    ["anatomical-heart", "หัวใจ"],
    ["brain", "สมอง"],
    ["eye", "ตา"],
    ["crutch", "ไม้ค้ำ"],
    ["wheelchair-symbol", "รถเข็น"],
    ["lotion-bottle", "โลชั่น"],
    ["razor", "มีดโกน"],
    ["barber-pole", "ตัดผม"],
    ["person-in-lotus-position", "นั่งสมาธิ"],
    ["flexed-biceps", "ออกกำลังกาย"],
    ["medical-symbol", "การแพทย์"],
    ["red-heart", "หัวใจแดง"],
    ["health-worker", "บุคลากรแพทย์"],
    ["sneezing-face", "เป็นหวัด"],
    ],
  },
  {
    key: "e_work", label: "งานและการเรียน", cover: "briefcase",
    items: [
    ["office-worker", "พนักงานออฟฟิศ"],
    ["busts-in-silhouette", "ทีมงาน"],
    ["bust-in-silhouette", "พนักงาน"],
    ["identification-card", "บัตรประจำตัว"],
    ["name-badge", "ป้ายชื่อ"],
    ["necktie", "เนกไท"],
    ["factory", "โรงงาน"],
    ["construction-worker", "ช่างก่อสร้าง"],
    ["mechanic", "ช่างซ่อม"],
    ["cook", "พ่อครัว"],
    ["farmer", "เกษตรกร"],
    ["technologist", "ไอที"],
    ["artist", "นักออกแบบ"],
    ["scientist", "นักวิทยาศาสตร์"],
    ["judge", "ทนาย"],
    ["pilot", "นักบิน"],
    ["firefighter", "นักดับเพลิง"],
    ["police-officer", "ตำรวจ"],
    ["teacher", "ครู"],
    ["student", "นักเรียน"],
    ["school", "โรงเรียน"],
    ["graduation-cap", "จบการศึกษา"],
    ["books", "หนังสือหลายเล่ม"],
    ["open-book", "หนังสือเปิด"],
    ["closed-book", "หนังสือ"],
    ["notebook", "สมุด"],
    ["pencil", "ดินสอ"],
    ["fountain-pen", "ปากกาหมึกซึม"],
    ["pen", "ปากกา"],
    ["crayon", "สีเทียน"],
    ["microscope", "กล้องจุลทรรศน์"],
    ["telescope", "กล้องดูดาว"],
    ["test-tube", "หลอดทดลอง"],
    ["globe-showing-asia-australia", "โลก"],
    ["desktop-computer", "คอมพิวเตอร์"],
    ["keyboard", "คีย์บอร์ด"],
    ["computer-mouse", "เมาส์"],
    ["printer", "เครื่องพิมพ์"],
    ["robot", "หุ่นยนต์"],
    ["link", "ลิงก์"],
    ["magnifying-glass-tilted-left", "ค้นหา"],
    ["floppy-disk", "บันทึกไฟล์"],
    ["battery", "แบตเตอรี"],
    ["flashlight", "ไฟฉาย"],
    ],
  },
  {
    key: "e_fun", label: "บันเทิงและกีฬา", cover: "party-popper",
    items: [
    ["party-popper", "ฉลอง"],
    ["confetti-ball", "ลูกบอลปาร์ตี้"],
    ["balloon", "ลูกโป่ง"],
    ["fireworks", "พลุ"],
    ["sparkler", "ประทัดไฟ"],
    ["sparkles", "ประกาย"],
    ["christmas-tree", "ต้นคริสต์มาส"],
    ["video-game", "เกม"],
    ["joystick", "จอยเกม"],
    ["game-die", "ลูกเต๋า"],
    ["slot-machine", "เสี่ยงโชค"],
    ["clapper-board", "หนัง"],
    ["movie-camera", "ถ่ายหนัง"],
    ["performing-arts", "ละคร"],
    ["artist-palette", "ศิลปะ"],
    ["musical-note", "เพลง"],
    ["musical-notes", "ดนตรี"],
    ["guitar", "กีตาร์"],
    ["microphone", "ไมโครโฟน"],
    ["headphone", "หูฟัง"],
    ["radio", "วิทยุ"],
    ["camera", "กล้องถ่ายรูป"],
    ["video-camera", "กล้องวิดีโอ"],
    ["circus-tent", "ละครสัตว์"],
    ["ferris-wheel", "ชิงช้าสวรรค์"],
    ["roller-coaster", "รถไฟเหาะ"],
    ["soccer-ball", "ฟุตบอล"],
    ["basketball", "บาสเกตบอล"],
    ["volleyball", "วอลเลย์บอล"],
    ["tennis", "เทนนิส"],
    ["badminton", "แบดมินตัน"],
    ["ping-pong", "ปิงปอง"],
    ["bowling", "โบว์ลิง"],
    ["flag-in-hole", "กอล์ฟ"],
    ["trophy", "ถ้วยรางวัล"],
    ["sports-medal", "เหรียญรางวัล"],
    ["1st-place-medal", "ที่หนึ่ง"],
    ["boxing-glove", "มวย"],
    ["person-running", "วิ่ง"],
    ["person-swimming", "ว่ายน้ำ"],
    ["person-biking", "ปั่นจักรยาน"],
    ["skateboard", "สเกตบอร์ด"],
    ["fishing-pole", "ตกปลา"],
    ["kite", "ว่าว"],
    ["teddy-bear", "ตุ๊กตาหมี"],
    ["puzzle-piece", "จิ๊กซอว์"],
    ["magic-wand", "ไม้กายสิทธิ์"],
    ["crystal-ball", "ลูกแก้ว"],
    ],
  },
  {
    key: "e_family", label: "ครอบครัวและสัตว์เลี้ยง", cover: "people-hugging",
    items: [
    ["people-hugging", "ครอบครัว"],
    ["baby", "ทารก"],
    ["child", "เด็ก"],
    ["boy", "เด็กผู้ชาย"],
    ["girl", "เด็กผู้หญิง"],
    ["man", "ผู้ชาย"],
    ["woman", "ผู้หญิง"],
    ["older-person", "ผู้สูงอายุ"],
    ["old-man", "คุณตา"],
    ["old-woman", "คุณยาย"],
    ["pregnant-woman", "ตั้งครรภ์"],
    ["love-letter", "จดหมายรัก"],
    ["two-hearts", "สองหัวใจ"],
    ["bouquet", "ช่อดอกไม้"],
    ["rose", "กุหลาบ"],
    ["tulip", "ทิวลิป"],
    ["cherry-blossom", "ซากุระ"],
    ["hibiscus", "ชบา"],
    ["dog", "สุนัข"],
    ["dog-face", "หน้าสุนัข"],
    ["cat", "แมว"],
    ["cat-face", "หน้าแมว"],
    ["paw-prints", "รอยเท้าสัตว์"],
    ["rabbit", "กระต่าย"],
    ["hamster", "หนูแฮมสเตอร์"],
    ["bird", "นก"],
    ["fish", "ปลา"],
    ["turtle", "เต่า"],
    ["butterfly", "ผีเสื้อ"],
    ["honeybee", "ผึ้ง"],
    ["pig-face", "หมู"],
    ["chicken", "ไก่"],
    ["cow", "วัว"],
    ],
  },
  {
    key: "e_travel", label: "เที่ยวและธรรมชาติ", cover: "beach-with-umbrella",
    items: [
    ["beach-with-umbrella", "ชายหาด"],
    ["desert-island", "เกาะ"],
    ["camping", "ตั้งแคมป์"],
    ["tent", "เต็นท์"],
    ["mountain", "ภูเขา"],
    ["snow-capped-mountain", "ภูเขาหิมะ"],
    ["volcano", "ภูเขาไฟ"],
    ["national-park", "อุทยาน"],
    ["hot-springs", "น้ำพุร้อน"],
    ["sunrise", "พระอาทิตย์ขึ้น"],
    ["sunset", "พระอาทิตย์ตก"],
    ["cityscape", "เมือง"],
    ["night-with-stars", "กลางคืน"],
    ["bridge-at-night", "สะพาน"],
    ["fountain", "น้ำพุ"],
    ["castle", "ปราสาท"],
    ["classical-building", "อาคารเก่า"],
    ["stadium", "สนามกีฬา"],
    ["statue-of-liberty", "เทพีเสรีภาพ"],
    ["mosque", "มัสยิด"],
    ["church", "โบสถ์"],
    ["hindu-temple", "วัด"],
    ["passport-control", "ตรวจคนเข้าเมือง"],
    ["customs", "ศุลกากร"],
    ["baggage-claim", "รับกระเป๋า"],
    ["passenger-ship", "เรือสำราญ"],
    ["sun", "แดด"],
    ["cloud", "เมฆ"],
    ["sun-behind-cloud", "แดดมีเมฆ"],
    ["cloud-with-rain", "ฝนตก"],
    ["umbrella-with-rain-drops", "ร่ม"],
    ["rainbow", "สายรุ้ง"],
    ["snowflake", "หิมะ"],
    ["palm-tree", "ต้นปาล์ม"],
    ["evergreen-tree", "ต้นสน"],
    ["deciduous-tree", "ต้นไม้ใหญ่"],
    ["four-leaf-clover", "โคลเวอร์"],
    ["herb", "สมุนไพร"],
    ["mushroom", "เห็ด"],
    ["star", "ดาว"],
    ["glowing-star", "ดาวเปล่งแสง"],
    ["crescent-moon", "พระจันทร์"],
    ["rocket", "จรวด"],
    ],
  },
]

/** โลโก้แบรนด์ — [ชื่อไฟล์, ชื่อแสดง, สีประจำแบรนด์] */
export const BRAND_ICONS = [
  ["line", "LINE", "#00C300"],
  ["facebook", "Facebook", "#0866FF"],
  ["messenger", "Messenger", "#0866FF"],
  ["instagram", "Instagram", "#FF0069"],
  ["x", "X (Twitter)", "#000000"],
  ["tiktok", "TikTok", "#000000"],
  ["youtube", "YouTube", "#FF0000"],
  ["whatsapp", "WhatsApp", "#25D366"],
  ["telegram", "Telegram", "#26A5E4"],
  ["discord", "Discord", "#5865F2"],
  ["reddit", "Reddit", "#FF4500"],
  ["pinterest", "Pinterest", "#BD081C"],
  ["snapchat", "Snapchat", "#FFFC00"],
  ["twitch", "Twitch", "#9146FF"],
  ["shopee", "Shopee", "#EE4D2D"],
  ["grab", "Grab", "#00B14F"],
  ["aliexpress", "AliExpress", "#FF4747"],
  ["ebay", "eBay", "#E53238"],
  ["airbnb", "Airbnb", "#FF5A5F"],
  ["uber", "Uber", "#000000"],
  ["google", "Google", "#4285F4"],
  ["gmail", "Gmail", "#EA4335"],
  ["googlemaps", "Google Maps", "#4285F4"],
  ["googledrive", "Google Drive", "#4285F4"],
  ["googleplay", "Google Play", "#414141"],
  ["apple", "Apple", "#000000"],
  ["netflix", "Netflix", "#E50914"],
  ["spotify", "Spotify", "#1ED760"],
  ["figma", "Figma", "#F24E1E"],
  ["github", "GitHub", "#181717"],
  ["notion", "Notion", "#000000"],
  ["dropbox", "Dropbox", "#0061FF"],
  ["zoom", "Zoom", "#0B5CFF"],
  ["paypal", "PayPal", "#002991"],
  ["visa", "Visa", "#1A1F71"],
  ["mastercard", "Mastercard", "#EB001B"],
  ["jcb", "JCB", "#0B4EA2"],
  ["americanexpress", "American Express", "#2E77BC"],
  ["discover", "Discover", "#FF6000"],
  ["googlepay", "Google Pay", "#4285F4"],
  ["applepay", "Apple Pay", "#000000"],
  ["samsungpay", "Samsung Pay", "#1428A0"],
  ["alipay", "Alipay", "#1677FF"],
  ["wechat", "WeChat Pay", "#07C160"],
  ["wise", "Wise", "#9FE870"],
  ["klarna", "Klarna", "#FFB3C7"],
  ["foodpanda", "foodpanda", "#D70F64"],
  ["kfc", "KFC", "#F40027"],
  ["burgerking", "Burger King", "#D62300"],
  ["cocacola", "Coca-Cola", "#D00013"],
  ["unilever", "Unilever", "#1F36C7"],
  ["dhl", "DHL", "#FFCC00"],
  ["fedex", "FedEx", "#4D148C"],
  ["ups", "UPS", "#150400"],
  ["shopify", "Shopify", "#7AB55C"],
  ["woocommerce", "WooCommerce", "#96588A"],
  ["stripe", "Stripe", "#635BFF"],
  ["xero", "Xero", "#13B5EA"],
  ["quickbooks", "QuickBooks", "#2CA01C"],
  ["wordpress", "WordPress", "#21759B"],
  ["trello", "Trello", "#0052CC"],
  ["asana", "Asana", "#F06A6A"],
  ["airtable", "Airtable", "#18BFFF"],
  ["claude", "Claude", "#D97757"],
  ["steam", "Steam", "#000000"],
  ["playstation", "PlayStation", "#0070D1"],
  ["shell", "Shell", "#FFD500"],
  ["toyota", "Toyota", "#EB0A1E"],
  ["honda", "Honda", "#E40521"],
  ["tesla", "Tesla", "#CC0000"],
  ["ikea", "IKEA", "#0058A3"],
  ["starbucks", "Starbucks", "#006241"],
  ["mcdonalds", "McDonalds", "#FBC817"],
]

/** โลโก้ธนาคารไทย ใช้ไฟล์ชุดเดิมที่ public/bank-logos — [รหัส, ชื่อธนาคาร, สีประจำธนาคาร] */
export const BANK_ICONS = [
  ["kbank", "กสิกรไทย", "#138f2d"],
  ["scb", "ไทยพาณิชย์", "#4e2e7f"],
  ["bbl", "กรุงเทพ", "#1e4598"],
  ["ktb", "กรุงไทย", "#1ba5e1"],
  ["bay", "กรุงศรีอยุธยา", "#fec43b"],
  ["ttb", "ทหารไทยธนชาต", "#1279be"],
  ["gsb", "ออมสิน", "#eb198d"],
  ["baac", "ธ.ก.ส.", "#4b9b1d"],
  ["ghb", "อาคารสงเคราะห์", "#f57d23"],
  ["kk", "เกียรตินาคินภัทร", "#199cc5"],
  ["tisco", "ทิสโก้", "#12549f"],
  ["cimb", "ซีไอเอ็มบี ไทย", "#7e2f36"],
  ["uob", "ยูโอบี", "#0b3979"],
  ["lhb", "แลนด์ แอนด์ เฮ้าส์", "#6d6e71"],
  ["tcrb", "ไทยเครดิต", "#0a4ab3"],
  ["ibank", "อิสลามแห่งประเทศไทย", "#184615"],
  ["icbc", "ไอซีบีซี (ไทย)", "#c50f1c"],
  ["citi", "ซิตี้แบงก์", "#1583c7"],
  ["sc", "สแตนดาร์ดชาร์เตอร์ด", "#0f6ea1"],
]

/** ชื่อไอคอน → โฟลเดอร์ที่เก็บ ใช้ประกอบเป็น path ตอนแสดงผล */
const GROUP_OF = Object.fromEntries(
  ICON_GROUPS.flatMap((g) => g.items.map(([name]) => [name, g.key])),
)

/** ชื่อไอคอนสีที่มีอยู่จริง — ไอคอนสีเก็บรวมโฟลเดอร์เดียว จึงเช็กแค่ว่ามีชื่อนี้ไหม */
const EMOJI_OF = Object.fromEntries(
  EMOJI_GROUPS.flatMap((g) => g.items.map(([name]) => [name, g.key])),
)

/**
 * แปลงค่าที่เก็บในฐานข้อมูลเป็น URL ของไฟล์ SVG
 * คืน null ถ้าค่าว่างหรือชี้ไปยังไอคอนที่ถูกถอดออกจากชุดไปแล้ว
 * ตัวเรียกต้องรองรับ null เสมอ เพราะข้อมูลเก่าอาจอ้างไอคอนที่ไม่มีอยู่แล้ว
 */
export function iconUrl(value) {
  if (!value || typeof value !== 'string') return null
  const [kind, name] = value.split(':')
  if (!name) return null
  if (kind === 'bank') return `bank-logos/${name}.svg`
  if (kind === 'brand') return `icons/brand/${name}.svg`
  if (kind === 'emoji') return EMOJI_OF[name] ? `icons/emoji/${name}.svg` : null
  if (kind === 'ms') {
    const group = GROUP_OF[name]
    return group ? `icons/${group}/${name}.svg` : null
  }
  return null
}

/** สีประจำแบรนด์/ธนาคารของค่านั้น — ไอคอนทั่วไปคืน null (ใช้สีตามบริบทที่วาง) */
export function iconBrandColor(value) {
  if (!value || typeof value !== 'string') return null
  const [kind, name] = value.split(':')
  if (kind === 'brand') return BRAND_ICONS.find((b) => b[0] === name)?.[2] ?? null
  if (kind === 'bank') return BANK_ICONS.find((b) => b[0] === name)?.[2] ?? null
  return null
}

/**
 * สีประจำกลุ่มของไอคอนทั่วไป — คืน null สำหรับแบรนด์/ธนาคาร (พวกนั้นใช้ iconBrandColor)
 * ไอคอนที่ผู้ใช้เลือกจึงมีสีของตัวเองตามหมวด (อาหารส้ม เดินทางฟ้า สุขภาพชมพู)
 * โดยไม่ต้องเพิ่มคอลัมน์สีในฐานข้อมูล
 */
export function iconGroupColor(value) {
  if (!value || typeof value !== 'string') return null
  const [kind, name] = value.split(':')
  if (kind !== 'ms') return null
  const group = ICON_GROUPS.find((g) => g.key === GROUP_OF[name])
  return group?.color ?? null
}

/**
 * ไอคอนตัวนี้ระบายสีมาในไฟล์แล้วหรือไม่
 * ที่ต้องรู้เพราะไอคอนสีย้อมทับไม่ได้ ต้องวาดด้วย <img> ส่วนชุดอื่นวาดด้วย mask
 * เพื่อให้เปลี่ยนสีตามบริบทได้ (ขาวบนแถบเข้ม เขียวในหมวดรายรับ)
 */
export function iconIsColor(value) {
  return typeof value === 'string' && value.startsWith('emoji:')
}

/** ชื่อไทยของไอคอน ใช้เป็น tooltip และข้อความบอกว่าเลือกอะไรอยู่ */
export function iconLabel(value) {
  if (!value || typeof value !== 'string') return ''
  const [kind, name] = value.split(':')
  if (kind === 'brand') return BRAND_ICONS.find((b) => b[0] === name)?.[1] ?? name
  if (kind === 'bank') return BANK_ICONS.find((b) => b[0] === name)?.[1] ?? name
  if (kind === 'emoji') {
    for (const g of EMOJI_GROUPS) {
      const hit = g.items.find(([n]) => n === name)
      if (hit) return hit[1]
    }
    return name
  }
  for (const g of ICON_GROUPS) {
    const hit = g.items.find(([n]) => n === name)
    if (hit) return hit[1]
  }
  return name ?? ''
}

/** จำนวนไอคอนทั้งหมดในชุด ใช้แสดงในหน้าตั้งค่า */
export const ICON_TOTAL =
  ICON_GROUPS.reduce((s, g) => s + g.items.length, 0) +
  EMOJI_GROUPS.reduce((s, g) => s + g.items.length, 0) +
  BRAND_ICONS.length +
  BANK_ICONS.length
