import { getCurrentActorSnapshot } from './auditActor'

export function buildLogEntry({
  activityType,
  description,
  oldValue = null,
  newValue = null,
  changeNote = '',
  walletEffect = null,
  status = 'success',
  errorMessage = null,
  actor,
}) {
  return {
    activityType,
    description,
    oldValue,
    newValue,
    changeNote,
    walletEffect,
    status,
    errorMessage,
    actor: actor === undefined ? getCurrentActorSnapshot() : actor,
  }
}

export const ACTIVITY_LABELS = {
  ADD_INCOME: 'เพิ่มรายรับ',
  ADD_EXPENSE: 'เพิ่มรายจ่าย',
  EDIT_INCOME: 'แก้ไขรายรับ',
  EDIT_EXPENSE: 'แก้ไขรายจ่าย',
  DELETE_TRANSACTION: 'ลบรายการ',
  CANCEL_TRANSACTION: 'ยกเลิกรายการ',
  PAY_PENDING: 'ชำระค้างชำระ',
  CASH_DEPOSIT: 'ฝากเงินสด',
  TRANSFER_TO_WALLET: 'ย้ายเงินสด → เงินโอน',
  WITHDRAW_FROM_TRANSFER: 'ถอนเงินโอน → เงินสด',
  SUB_CREATE: 'สร้างกระเป๋าตังค์',
  SUB_DELETE: 'ลบกระเป๋าตังค์',
  SUB_RENAME: 'เปลี่ยนชื่อกระเป๋า',
  SUB_DEPOSIT: 'ฝากเงินเข้ากระเป๋า',
  SUB_WITHDRAW: 'ถอนเงินจากกระเป๋า',
  SUB_TRANSFER: 'โอนระหว่างกระเป๋า',
  SUB_BORROW: 'ยืมเงินจากกระเป๋า',
  SUB_RETURN: 'คืนเงินกระเป๋า',
  RECEIVE_TAX_INVOICE: 'รับใบกำกับภาษี',
  IMPORT_DATA: 'นำเข้าข้อมูล',
  RESTORE_BACKUP: 'กู้คืนข้อมูล',
  ADD_INCOME_MAIN: 'รับเงิน',
  OPEN_BILL: 'เปิดบิลค้างชำระ',
  ADD_OTHER_INCOME: 'รับเงินประเภทอื่นๆ',
  OPEN_BILL_INCOME: 'เปิดบิลรอรับเงิน',
  RECEIVE_INCOME: 'รับเงินจากรายการรอ',
  CREATE_TAX_INVOICE: 'สร้างรอใบกำกับภาษี',
  DELETE_TAX_INVOICE: 'ยกเลิกรอใบกำกับภาษี',
  CREATE_PENDING: 'สร้างรายการค้างชำระ',
  DELETE_PENDING: 'ยกเลิกรายการค้างชำระ',
  SHOP_CREATE: 'สร้างร้าน',
  SHOP_SELECT: 'เข้าใช้งานร้าน',
  SHOP_UPDATE: 'แก้ไขร้าน',
  SHOP_DELETE: 'ลบร้าน',
  SHOP_RECOVER: 'กู้คืนร้าน',
  SHOP_BACKUP: 'สำรองข้อมูลร้าน',
  SETTINGS_BACKUP: 'สำรองการตั้งค่า',
  SETTINGS_RESTORE: 'กู้คืนการตั้งค่า',
  SETTINGS_SYNC_ALL_SHOPS: 'ซิงก์การตั้งค่าทุกร้าน',
  LOG_EXPORT: 'ดาวน์โหลดประวัติ',
  LOG_CLEAR_OLD: 'ล้างประวัติเก่า',
  REPORT_EXPORT: 'ส่งออกรายงาน',
  CATEGORY_CREATE: 'สร้างหมวดหมู่',
  CATEGORY_UPDATE: 'แก้ไขหมวดหมู่',
  CATEGORY_DELETE: 'ลบหมวดหมู่',
  VENDOR_CREATE: 'สร้างผู้ขาย',
  VENDOR_UPDATE: 'แก้ไขผู้ขาย',
  VENDOR_DELETE: 'ลบผู้ขาย',
  QUICK_ITEM_CREATE: 'สร้างรายการด่วน',
  QUICK_ITEM_UPDATE: 'แก้ไขรายการด่วน',
  QUICK_ITEM_DELETE: 'ลบรายการด่วน',
  CALENDAR_NOTE_CREATE: 'สร้างโน้ตปฏิทิน',
  CALENDAR_NOTE_UPDATE: 'แก้ไขโน้ตปฏิทิน',
  CALENDAR_NOTE_DELETE: 'ลบโน้ตปฏิทิน',
  UPLOAD_RECEIPT: 'อัปโหลดใบเสร็จ',
  UPLOAD_TAX_INVOICE_FILE: 'อัปโหลดไฟล์ใบกำกับภาษี',
  UPLOAD_FILE_FAILED: 'อัปโหลดไฟล์ไม่สำเร็จ',
  RECURRING_CREATE: 'สร้างรายการประจำ',
  RECURRING_UPDATE: 'แก้ไขรายการประจำ',
  RECURRING_DELETE: 'ลบรายการประจำ',
  RECURRING_PAID: 'จ่ายรายการประจำ',
  RECURRING_UNPAID: 'ยกเลิกการจ่ายรายการประจำ',
  RECURRING_SKIPPED: 'ข้ามรายการประจำ',
  RECURRING_GENERATE: 'สร้างรายการประจำรายเดือน',
  // ─── System management (home system) ────────────────────────
  SYS_USER_CREATE:    'สร้างผู้ใช้งาน (ระบบหลัก)',
  SYS_USER_UPDATE:    'แก้ไขผู้ใช้งาน (ระบบหลัก)',
  SYS_USER_DELETE:    'ลบผู้ใช้งาน (ระบบหลัก)',
  SYS_USER_BLOCK:     'บล็อกผู้ใช้งาน (ระบบหลัก)',
  SYS_USER_UNBLOCK:   'ปลดบล็อกผู้ใช้งาน (ระบบหลัก)',
  SYS_ROLE_CREATE:    'สร้าง Role (ระบบหลัก)',
  SYS_ROLE_UPDATE:    'แก้ไข Role (ระบบหลัก)',
  SYS_ROLE_DELETE:    'ลบ Role (ระบบหลัก)',
  // ─── Store management (in-store) ────────────────────────────
  STORE_USER_CREATE:  'สร้างพนักงาน',
  STORE_USER_UPDATE:  'แก้ไขพนักงาน',
  STORE_USER_DELETE:  'ลบพนักงาน',
  STORE_USER_BLOCK:   'บล็อกพนักงาน',
  STORE_USER_UNBLOCK: 'ปลดบล็อกพนักงาน',
  STORE_ROLE_CREATE:  'สร้าง Role (ร้านค้า)',
  STORE_ROLE_UPDATE:  'แก้ไข Role (ร้านค้า)',
  STORE_ROLE_DELETE:  'ลบ Role (ร้านค้า)',
}
